app = "modern-band-backend"  # You can change this to your preferred app name
primary_region = "bom"  # bombay - change to your preferred region

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false  # Keep the app running
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="modern_band_data"
  destination="/app/data" 